### ISSUE TITLE
Warming drawer temperatures unavailable

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele#26]
With the update https://github.com/HomeAssistant-Mods/home-assistant-miele/commit/c2ae8a626edb703096884ec6e84282e113c2609b info about warming drawer (Temperature, target temperature, starting time, elapsed time) is gone.

**Comment by kloknibor** [comment]
Hi @FransHalsjes this actually already happenend in 9f23e6b2746f0b251a5a4fc1a8127a398a98989f because according to the miele documentation this is not supported... See : https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf

A warming drawer is a dish warmer I suppose so number 25? Could you double check by going here and send me the top part of the /devices response (you need to authorize at the top right corner.

{
  "additionalProp1": {
    "ident": {
      "type": {
        "key_localized": "string",
        "value_raw": 1,
        "value_localized": "string"
      },

The value_raw is the one I'm interested in :-)

**Comment by kloknibor** [comment]
If it is indeed 25 I can push a quick fix for it, I just need to add the capabilities back into the code for number 25.

**Comment by FransHalsjes** [comment]
There you go. It's 25 indeed!
{
  "000160887079": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 25,
        "value_localized": "Warming drawer"
      },

**Comment by kloknibor** [comment]
commit 5973df249c66f8786d4eaa802626d0ec4695bf59 should solve your issue. Can you please check if thesensor types that are created all give some feedback and nothing is missing anymore? Thanks!

**Comment by kloknibor** [comment]
and when all is ok close this issue

**Comment by FransHalsjes** [comment]
Works like a charm again. Nothing missing anymore. Thanks!
