### ISSUE TITLE
hard time installing the component

### ISSUE THREAD

**Issue by reiniertc** [HomeAssistant-Mods/home-assistant-miele#54]
I have tried installing the component via HACS.
After rebooting, I see a notification in HA with a link to Miele.
I have to enter my Miele credentials for miele@home, but I always got a german error.

After removing the integration and reinstalling it, I dont get the notification to login to Miele anymore.
Also no entity or what so ever is present in HA. 

Performing a manual installation gives me the same result.

(I have the miele client id and secret setup in configuration.yaml)

Do you have any tips how to install the integration?

**Comment by naoisegolden** [comment]
For anyone arriving here like me, unable to make the integration work after deleting it and reinstalling it: I fixed it by deleting the token cache file and going through the whole installation process from scratch.

```
/config/.storage/.miele-token-cache
```

Since it's a hidden file (both `.storage` and `.miele-token-cache), you can access and delete it through the SSH terminal:

```sh
rm /config/.storage/.miele-token-cache
```

**Comment by naoisegolden** [comment]
I don't know if it's possible to delete the token cache automatically when the integration is deleted from HACS. If that's possible and someone can point me in the right direction, I could try to contribute that to the code.
