### ISSUE TITLE
Oven Start Time is offset not absolute time

### ISSUE THREAD

**Issue by doctorjames** [HomeAssistant-Mods/home-assistant-miele#7]
It is currently 20:58 and I've just set my Miele H6860BP  oven to come on at 7AM in the morning to preheat ready to bake bread when I get up.

`sensor.oven_start_time` is currently `10:02 `

So this field is clearly the time until the program starts, not the time at which the program starts.

**Comment by kloknibor** [comment]
Hi @doctorjames,

as quoted from the API of miele:

`the startTime object is representing relative starting time given in hours and minutes. the first value within the array equals the hours and the second value equals the minutes.`

So you are correct, but this is designed behaviour. You can find the Miele API over at : https://www.miele.com/developer/swagger-ui/swagger.html

**Comment by doctorjames** [comment]
I guessed that was misleading API behaviour, but it doesn't mean Home Assistant needs to adopt the semantically misleading name. Could we not have `sensor.oven_start_delay` or better still automatically add on the current time to get a more useful actual time that could be used in other automations?

**Comment by kloknibor** [comment]
@doctorjames I will take this into consideration. But this could also be solved on the side of your automation of course. I am not a big fan to rename the current sensor and changing what the current sensor outputs since I'm unsure if people are already using this in their automations and I would not want to break their automations. Added on that I prefer to keep the outputs of the Miele API the same to the sensor names in Hass to not cause any confusion. If there is more interest in this I might consider adding an absolute start time sensor to home assistant.
